version: "3.1"
services:
  rest:
    image: ailabreg.jnu.ac.kr/jnu/rest-oracle:latest
    environment:
    - TZ=Asia/Seoul
    - LANG=ko_KR.UTF-8
    - USER_NAME=dbuser
    - PASSWORD=/run/secrets/PASSWORD
    - SERVICE=XEPDB1
    - HOST=13.209.18.89
    - DB_PORT=32118
    - DB_TYPE=oracle
    - AUTH_QUERY=SELECT FIRST_NAME AS "sn", LAST_NAME AS "givenName", CONCAT(FIRST_NAME, LAST_NAME) AS "displayName", ID AS "uid", EMAIL AS "mail", ID AS "employeeNumber", CONCAT(CONCAT('빛가람대학교', ' | '), DEPARTMENT)  as "eduPersonScopedAffiliation", EMPLOYEE_TYPE as "employeeType" FROM DBUSER.USERS WHERE username = :USERID and PASSWORD=DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW(:PASSWORD, 'AL32UTF8'), 4)
    - ATTRIBUTE_QUERY=SELECT FIRST_NAME AS "sn", LAST_NAME AS "givenName", CONCAT(FIRST_NAME, LAST_NAME) AS "displayName", ID AS "uid", EMAIL AS "mail", ID AS "employeeNumber", CONCAT(CONCAT('빛가람대학교', ' | '), DEPARTMENT)  as "eduPersonScopedAffiliation", EMPLOYEE_TYPE as "employeeType" FROM DBUSER.USERS WHERE username = :USERID
    networks:
        idpapp:
            aliases:
             - rest
  idp:
    build:
      context: ./
    image:  ailabreg.jnu.ac.kr/jnu/shibboleth-idp:latest
    # image:  jnu-idp:latest
    environment:
     - TZ=Asia/Seoul
     - LANG=ko_KR.UTF-8
    ports:
    - 443:443
    - 80:80
    depends_on:
     - rest
    networks:
        idpapp:
    # volumes:
      # - ./logs:/opt/shib-jetty-base/logs
    # deploy:
    #     mode: replicated
    #     replicas: 2
networks:
    idpapp:

secrets:
    PASSWORD:
      file: PASSWORD.txt
