version: "3.1"
services:
  rest:
    image: docker.iugj.ac.kr/rest-oracle:latest
    environment:
    - TZ=Asia/Seoul
    - LANG=ko_KR.UTF-8
    - DB_USER=SYSTEM
    # - PASSWORD=/run/secrets/PASSWORD for HA config
    - DB_PASSWORD=${DB_PASSWORD}
    - SERVICE=ORCL
    - HOST=168.131.19.132
    - DB_PORT=1521
    - DB_TYPE=oracle
    - AUTH_QUERY=SELECT FIRST_NAME AS "surname", LAST_NAME AS "givenName", CONCAT(FIRST_NAME, LAST_NAME) AS "displayName", USERNAME AS "uid", EMAIL AS "mail", EMPLOYEE_NUMBER AS "employeeNumber", '빛가람대학교' as "organizationName",  DEPARTMENT as "organizationalUnitName", EMPLOYEE_TYPE as "employeeType" FROM DBUSER.USERS WHERE username = :USERID and PASSWORD=DBMS_CRYPTO.HASH(UTL_I18N.STRING_TO_RAW(:PASSWORD, 'AL32UTF8'), 4)
    - ATTRIBUTE_QUERY=SELECT FIRST_NAME AS "surname", LAST_NAME AS "givenName", CONCAT(FIRST_NAME, LAST_NAME) AS "displayName", USERNAME AS "uid", EMAIL AS "mail", EMPLOYEE_NUMBER AS "employeeNumber", '빛가람대학교' as "organizationName",  DEPARTMENT as "organizationalUnitName", EMPLOYEE_TYPE as "employeeType" FROM DBUSER.USERS WHERE username = :USERID
    # secrets:
      # DB_PASSWORD
    networks:
        idpapp:
            aliases:
             - rest
  idp:
    build:
        context: ./
        args:
            - IDP_SCOPE=jnu.ac.kr
            - IDP_HOST_NAME=idps2.jnu.ac.kr 
            - IDP_ENTITYID=https://idps2.jnu.ac.kr/idp/shibboleth
            - IDP_KEYSTORE_PASSWORD=changeme 
            - IDP_SEALER_PASSWORD=changeme 
    image: docker.iugj.ac.kr/jnu/shibboleth-idp:latest
    # image:  jnu-idp:latest
    environment:
     - TZ=Asia/Seoul
     - LANG=ko_KR.UTF-8
    ports:
    - 443:443
    - 80:80
    depends_on:
     - rest
    networks:
        idpapp:
    # secrets: #for HA
    # - DB_PASSWORD
    # - REALM
    # volumes:
      # - ./logs:/opt/shib-jetty-base/logs
    # deploy:
    #     mode: replicated
    #     replicas: 2
networks:
    idpapp:
secrets:
    DB_PASSWORD:
      file: DB_PASSWORD.txt
    REALM:
      file: REALM.txt
