version: "3.1"
services:
  rest:
    image: docker.iugj.ac.kr/rest-oracle:latest
    environment:
    - TZ=Asia/Seoul
    - LANG=ko_KR.UTF-8
    - DB_USER=hr
    # - PASSWORD=/run/secrets/PASSWORD for HA config
    - DB_PASSWORD=${DB_PASSWORD}
    - SERVICE=xe
    - HOST=52.79.152.235
    - DB_PORT=49161
    - DB_TYPE=oracle
    - AUTH_QUERY=SELECT * HR.EMPLOYEES WHERE EMPLOYEE_ID = :USERID and PASSWORD=:PASSWORD
    - ATTRIBUTE_QUERY=SELECT CONCAT(FIRST_NAME, LAST_NAME) AS "displayName", EMPLOYEE_ID AS "uid", EMAIL AS "mail", EMPLOYEE_ID AS "employeeNumber", 'IU-GJ' as "organization", 'univcode' as "organizationCode",  DEPARTMENT_ID as "division", 'student' as "userType" FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = :USERID
    # secrets:
      # DB_PASSWORD
    networks:
        idpapp:
            aliases:
             - rest
  idp:
    build:
        context: ./
        args:
            - IDP_SCOPE=iugj.ac.kr
            - IDP_HOST_NAME=idp.iugj.ac.kr 
            - IDP_ENTITYID=https://idp.iugj.ac.kr/idp/shibboleth
            - IDP_KEYSTORE_PASSWORD=04343 
            - IDP_SEALER_PASSWORD=04343 
            - IDP_ORG_DISPLAYNAME=빛가람대학교
            - IDP_ORG_HOMEPAGE=http://www.iugj.ac.kr
            - IDP_FORGOT_PASSWORD_URL=http://www.iugj.ac.kr/forgot-password
            - IDP_CHANGE_PASSWORD_URL=http://www.iugj.ac.kr/change-password
            - IDP_SUPPORT_URL=https://support.example.org/help

    image: docker.iugj.ac.kr/kwu/shibboleth-idp:latest
    # image:  jnu-idp:latest
    environment:
     - TZ=Asia/Seoul
     - LANG=ko_KR.UTF-8
    ports:
    - 443:443
    - 80:80
    depends_on:
     - rest
    networks:
        idpapp:
    # secrets: #for HA
    # - DB_PASSWORD
    # - REALM
    # volumes:
      # - ./logs:/opt/shib-jetty-base/logs
    # deploy:
    #     mode: replicated
    #     replicas: 2
networks:
    idpapp:
secrets:
    DB_PASSWORD:
      file: DB_PASSWORD.txt
    REALM:
      file: REALM.txt
